Add ESHP custom axis
googlefonts/axisregistry pull request #56
Opened 2022-07-27 23:02 UTC by vv-monsalve

PR to follow up on the inclusion of the new custom axis `ESHP` https://github.com/googlefonts/axisregistry/issues/15

2022-08-10 20:01 UTC, chrissimpkins requested changes

2022-08-10 20:01 UTC, chrissimpkins commented on Lib/axisregistry/data/element_shape.textproto
> +tag: "ESHP"
Decision made to revise this to "ELSP" from "ESHP"

2022-08-10 20:08 UTC, chrissimpkins requested changes

2022-08-10 20:08 UTC, chrissimpkins commented on Lib/axisregistry/data/element_shape.textproto
> +tag: "ESHP"
```suggestion
tag: "ELSP"
```

2022-08-10 20:09 UTC, chrissimpkins commented on Lib/axisregistry/data/element_shape.textproto
> +tag: "ESHP"
Addressed in https://github.com/googlefonts/axisregistry/pull/56/commits/aa483aa61e89b1f79079119cf239f6c4dc3a7047

2022-08-15 18:18 UTC, davelab6 commented
This needs images before merging, and description check with Sarah.

2022-09-23 20:59 UTC, vv-monsalve commented
Display name + Tag under revision #78

2022-09-28 16:38 UTC, chrissimpkins commented
https://github.com/googlefonts/axisregistry/pull/78#issuecomment-1261142617

2022-09-28 18:21 UTC, chrissimpkins approved these changes

2022-09-28 18:21 UTC, merged

2022-09-29 23:18 UTC, chrissimpkins commented
Merged to google/fonts main in https://github.com/google/fonts/pull/5333

2022-10-18 05:00 UTC, chrissimpkins commented
Let's move this axis registration to production so that we can prepare for the Handjet sandbox push.

https://github.com/google/fonts/pull/5426#discussion_r997718157