HyperExpansion axis added
googlefonts/axisregistry pull request #79
Opened 2022-09-21 15:45 UTC by RosaWagner

Closes #11 

For the fallbacks, I don't think it is necessarily what we shall do, but these are the current fallback for Readex Pro and Lexend (although not sure they will follow the exact same value).

2022-09-21 19:14 UTC, vv-monsalve commented
> (although not sure they will follow the exact same value).

This, among other reasons, is why we are currently not registering axis with fallback positions. Only declaring Min to Max range values plus the required `Default` fallback.

Solving the per family named instances is part of the future solutions needed but so far out of the scope when onboarding the current projects.

cc @evanwadams, @davelab6

2022-09-22 09:47 UTC, RosaWagner commented
Yep, I am expecting that too. 

For Min and Max, I guess the decision that has to be taken is if it follows the already used style names (Deca/Zetta) or something else.

2022-09-23 14:14 UTC, chrissimpkins commented on Lib/axisregistry/data/hyper_expansion.textproto
> +precision: 1
Should this be `-1`?

2022-09-23 14:20 UTC, chrissimpkins commented on Lib/axisregistry/data/hyper_expansion.textproto
> +description: "Expansion of inner and outer space of glyphs."
Per Viv: we should expand on definition to describe how this will be distinct from space axis

2022-09-23 14:22 UTC, chrissimpkins requested changes
Requests inline

2022-09-23 14:26 UTC, chrissimpkins commented on Lib/axisregistry/data/hyper_expansion.textproto
> +description: "Expansion of inner and outer space of glyphs."
OK to address this in sandbox post-merge if necesssary

2022-09-23 14:33 UTC, merged

2022-09-23 20:11 UTC, chrissimpkins commented
git subtree pulled into google/fonts in https://github.com/google/fonts/pull/5301